name: CI-CD-Flask-S3-ElasticBeanstalk
env:
  EB_S3_BUCKET_NAME   : "koval-flask-s3"
  EB_APPLICATION_NAME : "Koval-Flask"
  EB_ENVIRNMENT_NAME  : "Koval-Flask-Prod"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "us-east-1"

on:
  push:
    branches: 
      - master

jobs:
  # This workflow contains a single job called "build"
  CI-step:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone GITHUB repository
        uses: actions/checkout@v2
        
      - name: Create a package archive
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
