name: CI-CD-Flask-S3-ElasticBeanstalk
env:
  EB_S3_BUCKET_NAME   : "koval-flask-s3"
  EB_APPLICATION_NAME : "Koval-Flask"
  EB_ENVIRNMENT_NAME  : "Koval-Flask-Prod"
  EB_PACKAGE_NAME: "flask_app_${{ github.sha }}"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches: 
      - master

jobs:
  CI-step:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GITHUB repo
        uses: actions/checkout@v2

      - name: Create a package archive
        run: zip -r ${{ env.EB_PACKAGE_NAME }} ./ -x *git*
      
      - name: COnfigure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
        
      - name: Copy package artifact to S3
        run: aws s3 cp ${{ env.EB_PACKAGE_NAME }} s3://${{ env.EB_S3_BUCKET_NAME }}/

